### ISSUE TITLE
Need help with where this fits in the scheme of things.

### ISSUE THREAD

**Issue by Just-another-pleb** [sparkfun/Qwiic_SerLCD_Py#1]
(Me again)

Sorry, but I am going in circles with this display.

[https://learn.sparkfun.com/tutorials/avr-based-serial-enabled-lcds-hookup-guide](url)

I've found this in my journey on how to connect it.

I've seen this QWIIC mentioned but have no idea what it is or how to use it.

But in finding it, and seeing that there is python code, I'm guessing it is for the RasPi - or equivilent.

Can you explain  where/how this is used - or if it can be used - to talk to the display?

**Comment by Just-another-pleb** [comment]
Plodding along trying to get this installed (RasPi3a) I get this error:

```
pi@alarmclock:~/Desktop/Qwiic_SerLCD_Py-master/dist$ ls
sparkfun_qwiic_serlcd-0.0.1.tar.gz
pi@alarmclock:~/Desktop/Qwiic_SerLCD_Py-master/dist$ pip install sparkfun_qwiic_serlcd-0.0.1.tar.gz 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./sparkfun_qwiic_serlcd-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-kEQ7Qk/setup.py", line 44, in <module>
        with io.open(path.join(here, "DESCRIPTION.rst"), encoding="utf-8") as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-kEQ7Qk/DESCRIPTION.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-kEQ7Qk/
pi@alarmclock:~/Desktop/Qwiic_SerLCD_Py-master/dist$ 
```

**Comment by Just-another-pleb** [comment]
Good news.

(Don't know how/why)

But it    isnow installed and I can run the python scripts.

Now I just need to work out how to get what I want doing done.
