### ISSUE TITLE
The example files.

### ISSUE THREAD

**Issue by Just-another-pleb** [sparkfun/Qwiic_SerLCD_Py#2]
Running the "console to display" example it asks for me to type something to be displayed.

I type "blah" and this happens:

```
pi@alarmclock:~/Desktop/Qwiic_SerLCD_Py-master/examples$ python ex12_qwiic_serlcd_console_input_to_display.py 

SparkFun Qwiic SerLCD   Example 12


Type CTRL+C to end.

blah
Please type something to display on the LCD: Traceback (most recent call last):
  File "ex12_qwiic_serlcd_console_input_to_display.py", line 83, in <module>
    runExample()
  File "ex12_qwiic_serlcd_console_input_to_display.py", line 73, in runExample
    user_input = input("Please type something to display on the LCD: ")
  File "<string>", line 1, in <module>
NameError: name 'blah' is not defined
pi@alarmclock:~/Desktop/Qwiic_SerLCD_Py-master/examples$ 
```

**Comment by Just-another-pleb** [comment]
Good news.   I found the problem and now it is working.

But I would like to ask for some help.

The example files/scripts sort of work.
umber 2 and 13.   They adjust the backlight.

Weirdly 2 works fine - cycling form Red to Orange.

But 13 doesn't work too good.

The screen colours don't match what the text is saying.   The weird thing is that this one waits 5 seconds between cycles, and 2 waits only 1 second.

Anyway, I am wanting to ask:
From where does the text come when I adjust the back light?
Python or the AVR?

If python, where are these files?

I would like to get rid of the messages.   They disrupt things being displayed on the screen and positioning.
